### ISSUE TITLE
Browser prompts will make the virtual keyboard untargetable

### ISSUE THREAD

**Issue by PetersenArne** [YoeDistro/yoe-kiosk-browser#11]
Hi,
First of all, thank you for your work!

I wanted to use your minimalist browser for my project but encountered some issues with authentication (htdigest) and standard browser prompts. The virtual keyboard is always rendered underneath the prompts, z-axis wise. My understanding is that this is simply how browser modals work, as they are meant to be in the foreground.

So I forked your GitHub ([myFork](https://github.com/PetersenArne/yoe-kiosk-browser)) and implemented custom prompts to resolve the issue.
Since this would be my first contribution, I wanted to ask via an issue if this is of interest to you, before I clean up my code and approach a pull request.

Best regards,
Arne

**Comment by cbrake** [comment]
Thanks for sharing these ideas!

These look like good additions, as Authentication is something users of this project can deal with, so I am interested in merging these changes.

The changes are extensive. Could you provide some before and after screenshots just to get a sense for what problem this solves?

It also might be nice to have these options be configurable features -- can be enabled if needed or not. Again, I don't completely understand the problem being solved, so maybe it makes sense to have them in all the time.

Lastly, it might be good to include screenshots in the README for these options so it is clear to users what they do.

Thanks again, looking forward to learning more about your improvements!

**Comment by PetersenArne** [comment]
My pleasure! It’s great to contribute.

The default login modal looks like this:
![Screenshot from 2024-09-17 09-48-37](https://github.com/user-attachments/assets/39bf3f49-9e08-46f2-8018-1927451b6047)

In this case, the virtual keyboard appears beneath the modal in the z-index, rendering the keyboard unusable and preventing successful login. The same issue occurs with dialog prompts.

This can be resolved by using custom dialogs, as shown here:
![login](https://github.com/user-attachments/assets/18a8c783-e462-4be4-8103-f9975398f338)


I’ve updated [my fork](https://github.com/PetersenArne/yoe-kiosk-browser) to be cleaner and added some options to the environment file. These options will also require an updated BitBake recipe. GitHub doesn’t allow me to attach mine here, but I can share it for review if needed.

Best regards,
Arne

**Comment by cbrake** [comment]
Thanks for the screenshots -- your custom dialogs look much better than the original!

Perhaps open a PR when you are ready and we can start discussing there.

**Comment by PetersenArne** [comment]
Sure, i'll open a PR.
