### ISSUE TITLE
yoe kiosk browser with qt5

### ISSUE THREAD

**Issue by cryptobharathi** [YoeDistro/yoe-kiosk-browser#14]
I have a project requirement to use light weight web browser with qt5, which can run with eglfs/wayland backend. Finally i plan to choose yoe kiosk browser, but it looks, it uses qt6. Is there is any option that "yoe kiosk browser " can be build with qt5, looking for suggestions.

Thanks and Regards,
Bharathi

**Comment by cbrake** [comment]
I've never tried, but I suspect there will be quite a few QML changes to backport to qt5 -- may be possible, but you may lose a few features. 

I'll close this for now as I don't think this is anything this project can help with as qt5 is not in our roadmap. You are welcome to reopen or leave additional comments if you like.

**Comment by kraj** [comment]
It used to work ok with qt5 a year or so ago so you might be in luck if it works today unmodified you can take an older snapshot that might help

**Comment by cryptobharathi** [comment]
@kraj  and @cbrake Will check your suggestions, Thanks for sharing the details.

**Comment by cbrake** [comment]
Great idea @kraj -- I checked the Yoe Distro changelog, and it looks like we switched from Qt5 to Qt6 around 2023-06:

https://github.com/YoeDistro/yoe-distro/blob/master/CHANGELOG.md#202306---2023-06-30

However, the first commit for the Yoe Kiosk browser was July 12, 2023, so we must have started that project after we switched to Qt6.

I think this is the project we used before that on Qt5:

https://github.com/cbrake/kiosk-browser/tree/qt-webengine

**Comment by cryptobharathi** [comment]
Thanks for point the right link @cbrake , will try this at my end. 

Thanks and Regards,
Bharathi
